# **************************************************************************************
# ******************* Open Source SHP Builder - Community Links File *******************
# **************************************************************************************
#
# Community Links Version 2.00
# Open Source SHP Builder 3.38
# Updated At: 01/10/2024
# -------------------------------------
#
# This file works in the following way:
#
#  # = comment
#  [] = separators for category name
#  $ $ = separatos for site url
#  < > = separators for a site name
#
#  Note: Do not use the symbols above in the description of url or site name.
#
#  They MUST appear in this exact order and please, do not jump lines without comment them
#
#  Here's a sample
#
# [Category1]
# $https://www.mysite.com$
# <My Site>
# $https://www.blahblahblah2.net$
# <Blah Blah Blah v2>
# [Category 2]
# $https://www.ppmsite.com$
# <Project Perfect Mod: We save modders!>
# [Best Source Sites]
# $https://www.cnc-source.com$
# <CnC Source>
#
# Note: Unlike this example, try following an alphabetic order for the sites
#
#
[Tiberian Dawn]
$https://cnc-comm.com/$
<CnC Communications Center>
$https://cnc2sw.ppmsite.com/$
<CnC Meets Star Wars>
$https://www.cncnz.com/$
<CNCNZ.com>
$https://www.ppmsite.com$
<Project Perfect Mod>
$https://www.tibed.net$
<TibEd.net (Tools)>
$https://dawn.tiberiumweb.org$
<Tiberium Web>
$https://xhp.xwis.net$
<XCC Homepage (Tools)>
#
#
[Red Alert 1]
$https://cnc-comm.com/$
<CnC Communications Center>
$https://www.cncnz.com/$
<CNCNZ.com>
$https://www.ppmsite.com$
<Project Perfect Mod>
$https://members.tripod.com/red_alert_website/index.htm$
<Red Alert Arsenal>
$https://www.sharoma.com/ral/index.htm$
<Red Alert League>
$https://www.tibed.net$
<TibEd.net (Tools)>
$https://xhp.xwis.net$
<XCC Homepage (Tools)>
#
#
[TS Editing]
$https://ppmforums.com/forum-24/tiberian-sun-editing-forum/$
<Project Perfect Mod TS Editing Forums>
$https://forums.renegadeprojects.com/index.php?act=idx$
<Renegade Projects>
$https://forums.revora.net$
<Revora Creative Network>
$https://www.tiberiumweb.org$
<Tiberium Web>
#
#
[TS General]
$https://www.cnc-comm.com$
<CnC Communications Center>
$https://www.cncguild.net$
<CnC Guild>
$https://www.cncworld.org$
<CnC World>
$https://www.cncnz.com$
<CNCNZ>
$https://www.ppmsite.com$
<Project Perfect Mod>
$https://sun.tiberiumweb.org$
<Tiberium Web>
#
#
[TS Resources]
$https://www.ppmsite.com$
<Project Perfect Mod>
$https://www.tiberiumweb.org$
<Tiberium Web>
$https://www.yrargentina.com$
<YR Argentina>
#
#
[TS Tools]
$https://get3ds2vxl.ppmsite.com$
<3ds2Vxl>
$https://github.com/otherdeniz/CnC_RulesEditor/$
<CnC RulesEditor>
$https://www.ppmsite.com$
<Project Perfect Mod>
$https://www.tibed.net$
<TibEd>
$https://vinifera.readthedocs.io/en/latest/$
<Vinifera>
$https://xhp.xwis.net$
<XCC Homepage>
#
#
[RA2 Editing]
$https://www.modenc.renegadeprojects.com/$
<Modding Encyclopedia :: ModEnc>
$https://ppmforums.com/forum-26/red-alert-2-editing-forum/$
<Project Perfect Mod RA2 Editing Forums>
$https://forums.renegadeprojects.com/index.php$
<Renegade Projects>
$https://forums.revora.net$
<Revora Creative Network>
#
#
[RA2 General]
$https://www.cncguild.net$
<CnC Guild>
$https://www.cncnz.com$
<CNCNZ>
$https://www.cncworld.org$
<CnC World>
$https://www.ppmsite.com$
<Project Perfect Mod>
#
#
[RA2 Resources]
$https://launchpad.net/ares/$
<Ares>
$https://www.ppmsite.com/ddmtemp/$
<Dead Dragon Mods>
$https://www.migeater.net/$
<Mig Eater Studios>
$https://www.ppmsite.com$
<Project Perfect Mod>
$https://www.yrargentina.com$
<YR Argentina>
#
#
[RA2 Tools]
$https://get3ds2vxl.ppmsite.com$
<3ds2Vxl>
$https://launchpad.net/ares/$
<Ares>
$https://github.com/otherdeniz/CnC_RulesEditor/$
<CnC RulesEditor>
$https://dc.strategy-x.com$
<DCoder`s Coding Realm>
$https://marshall.strategy-x.com/$
<Marshall Industries>
$https://github.com/Phobos-developers/Phobos/$
<Phobos>
$https://www.ppmsite.com$
<Project Perfect Mod>
$https://www.tibed.net/$
<TibEd>
$https://vk.cncguild.net/$
<VK's Home>
$https://xhp.xwis.net$
<XCC Homepage>
$https://github.com/Xkein/YRDynamicPatcher$
<YR Dynamic Patcher>
#
#
[OpenRA]
$https://www.openra.net/$
<OpenRA.net (official website)>
$httsp://forum.openra.net$
<OpenRA Forums>
$https://ppmforums.com/forum-929/openra-editing-forums/$
<OpenRA Editing Forums (at PPM)>
$https://github.com/OpenRA/OpenRA$
<OpenRA development (on Github)>
#
#
[Online Gaming Services]
$http://cncnet.org/$
<CnCNet (TD/RA1/TS/RA2) (Best)>
$http://www.openra.net/$
<OpenRA (RA1/TD/D2K/TS)>
$http://www.xwis.net$
<XWIS (TD/RA1/TS/FS/RA2/YR)>
#
#
[The First Decade Solutions]
$https://github.com/CnCNet/cnc-ddraw$
<CnC-DDraw>
$https://www.cncnz.com/hosted-projects/command-patch/the-first-decade-unofficial-patch/$
<Unofficial TFD Patch 1.03>
$https://xhp.xwis.net/cgi-bin/forum.cgi?a=26;mid=13914$
<TFD ShortCut Installer (also fixes registry for modders)>
$https://ppmforums.com/topic-10681/is-your-cc-95-crashing-at-the-borders-of-the-map/$
<Fixing Crash on Border of big TD maps>
$https://ppmforums.com/topic-10447/tfd-problems-ask-nyerguds-he-solves-everything/$
<Random TFD Solutions (Ignore problem 3)>
#
#
[Non-English CnC Sites]
$https://www.cnchq.de$
<CnC HQ.de (German)>
$https://www.united-forum.de/cci/$
<CnC Inside.de (German)>
$https://www.cncsaga.com/$
<CnC Saga.Com (French)>
$https://www.timeofwar.com$
<CnC Time Of War (French)>
$https://www.united-forum.de/$
<CnC United Forum (German)>